---
- name: NextCloud
  hosts: server
  gather_facts: no

  tasks:
    - name: Set Moscow timezone
      community.general.timezone:
        name: Europe/Moscow

    - name: Update and upgrade software
      ansible.builtin.apt:
        update_cache: true
        upgrade: "yes"

    - name: Install necessary packages
      ansible.builtin.apt:
        pkg:
          - apache2

          - libapache2-mod-php
          - php-curl
          - php-gd
          - php-json
          - php-mbstring
          - php-xml
          - php-zip
          - php-pgsql

          - postgresql-all
          - acl

          - unzip

          - python3-pip
        state: present

    - name: Install necessary Python packages
      ansible.builtin.pip:
        name: psycopg2
        extra_args: --break-system-packages

    - name: Download and unpack NextCloud
      ansible.builtin.unarchive:
        dest: "/var/www/html"
        src: "https://download.nextcloud.com/server/releases/latest.zip"
        remote_src: true
        owner: "www-data"
        group: "www-data"
        creates: "/var/www/html/nextcloud"

    - name: Create PostgreSQL user
      become: true
      become_user: postgres
      community.postgresql.postgresql_user:
        name: nextcloud
        password: nextcloud

    - name: Create PostgreSQL database
      become: true
      become_user: postgres
      community.postgresql.postgresql_db:
        name: nextcloud
        owner: nextcloud
